# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    expose:
      - 27017

  app:
    image: "node"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
      - DATA=mongodb://mongo:27017/TravelMate
    volumes:
      - /home/romeo/Desktop/TravelMate/Server/node:/home/node/app
    ports:
      - "8095:8095"
    expose:
      - 8095
    command: "npm start"
    links:
      - mongo
    depends_on:
      - mongo
      

#For Debug
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - mongo
    depends_on:
      - mongo
